# NatLibFi/KB maintenance strategy

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:30"
      timezone: "Europe/Helsinki"
    target-branch: "test"
    pull-request-branch-name:
      separator: "-"
